Repository selab-hs/SE-Community-Service, pull requests merged in 2023-10, with the labels that each got.

#54 Feature/comments
  build.gradle
  src/main/java/com/core/service/board/application/BoardService.java
  src/main/java/com/core/service/comment/application/.keep
  src/main/java/com/core/service/comment/application/CommentService.java
  src/main/java/com/core/service/comment/domain/.keep
  src/main/java/com/core/service/comment/domain/Comment.java
  src/main/java/com/core/service/comment/domain/converter/CommentConverter.java
  src/main/java/com/core/service/comment/dto/.keep
  src/main/java/com/core/service/comment/dto/request/CreateCommentRequest.java
  src/main/java/com/core/service/comment/dto/request/ReadCommentRequest.java
  src/main/java/com/core/service/comment/dto/request/UpdateCommentRequest.java
  src/main/java/com/core/service/comment/dto/response/ReadCommentResponse.java
  src/main/java/com/core/service/comment/infrastructure/.keep
  src/main/java/com/core/service/comment/infrastructure/CommentRepository.java
  src/main/java/com/core/service/comment/presentaion/.keep
  src/main/java/com/core/service/comment/presentaion/CommentController.java
  src/main/java/com/core/service/common/response/dto/ResponseMessage.java
Labels: develop

#65 [Front/Member/Edit] Member 유효성 검사 및 회원 정보 변경 진행
  src/main/java/com/hs/selab/auth/application/AuthService.java
  src/main/java/com/hs/selab/auth/presentation/AuthRestController.java
  src/main/java/com/hs/selab/common/response/dto/ResponseMessage.java
  src/main/java/com/hs/selab/error/dto/ErrorMessage.java
  src/main/java/com/hs/selab/error/exception/member/NotExistUserInfoException.java
  src/main/java/com/hs/selab/member/application/MemberService.java
  src/main/java/com/hs/selab/member/presentaion/MemberRestController.java
  src/main/java/com/hs/selab/member/presentaion/ui/MemberController.java
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/css/font.css
  src/main/resources/static/css/header/header.css
  src/main/resources/static/css/member/member-edit.css
  src/main/resources/static/js/member/login.js
  src/main/resources/static/js/member/member-edit.js
  src/main/resources/static/js/member/member-header.js
  src/main/resources/static/js/member/sign-up.js
  src/main/resources/templates/fragments/head/head.html
  src/main/resources/templates/fragments/head/member-edit-head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/member-header.html
  src/main/resources/templates/fragments/script.html
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/layout/login-layout.html
  src/main/resources/templates/layout/member-edit-layout.html
  src/main/resources/templates/layout/sign-up-layout.html
  src/main/resources/templates/member/edit.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/sign-up.html
Labels: develop

#68 [Repactoring/Member-State] 유저 권한 및 역할 분리
  src/main/java/com/hs/selab/auth/domain/UserDetail.java
  src/main/java/com/hs/selab/board/application/BoardService.java
  src/main/java/com/hs/selab/comment/application/CommentService.java
  src/main/java/com/hs/selab/member/domain/Member.java
  src/main/java/com/hs/selab/member/domain/vo/MemberState.java
  src/main/java/com/hs/selab/member/domain/vo/RoleType.java
  src/main/java/com/hs/selab/member/dto/response/MemberResponse.java
  src/main/java/com/hs/selab/post/application/PostService.java
Labels: repactoring

#71 [Feature/Front/Board-Nav] 헤더 Nav bar boardModel 카테고리 변경
  src/main/java/com/hs/selab/board/presentaion/BoardRestController.java
  src/main/java/com/hs/selab/common/response/dto/ResponseMessage.java
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/js/member/login.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/member-header.html
Labels: develop

#74 [Feature/Front/Board-Template]
  src/main/resources/static/assets/css/main.css
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/fragments/member-header.html
  src/main/resources/templates/index.html
Labels: develop

#76 [Fix/Front/Directory] 경로 설정 위치 작성 변경
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/board/view-board-list.html
  src/main/resources/templates/fragments/head/head.html
  src/main/resources/templates/fragments/head/login-head.html
  src/main/resources/templates/fragments/head/member-edit-head.html
  src/main/resources/templates/fragments/head/new-post-head.html
  src/main/resources/templates/fragments/head/sign-up-head.html
  src/main/resources/templates/fragments/script.html
Labels: bug

#79 [Fix/Jwt-Expired] Jwt 만료 예외처리 응답
  src/main/java/com/hs/selab/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/hs/selab/auth/infrastructure/LocalContextHolder.java
  src/main/java/com/hs/selab/auth/infrastructure/authentication/DefaultAuthenticationStrategy.java
  src/main/java/com/hs/selab/auth/infrastructure/authentication/GetAuthenticationStrategy.java
  src/main/java/com/hs/selab/auth/infrastructure/authentication/SetAuthenticationStrategy.java
  src/main/java/com/hs/selab/auth/resolver/AuthArgumentResolver.java
  src/main/java/com/hs/selab/auth/token/TokenProvider.java
  src/main/java/com/hs/selab/config/security/SecurityFilterConfig.java
  src/main/java/com/hs/selab/error/dto/ErrorMessage.java
  src/main/java/com/hs/selab/error/exception/member/SeExpiredJwtException.java
  src/main/java/com/hs/selab/error/exception/member/SeJwtException.java
  src/main/resources/static/js/member/login.js
  src/main/resources/static/js/member/member-edit.js
  src/main/resources/static/js/member/sign-up.js
Labels: bug

#84 [Feature/Front/Boards-Image] 게시판 이미지, 유저 이미지 변경
  src/main/resources/static/assets/css/main.css
  src/main/resources/static/images/free-forum.png
  src/main/resources/static/images/notice.png
  src/main/resources/static/images/user-post.svg
  src/main/resources/static/images/user.png
  src/main/resources/static/images/users.png
  src/main/resources/static/js/post/view-post.js
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/board/view-board-list.html
Labels: develop

#86 [Feature/Front/Boards-Image] 게시판 별 이미지 구분
  src/main/resources/static/assets/css/main.css
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/images/free-forum2.png
  src/main/resources/static/images/notice2.png
  src/main/resources/templates/board/view-board-list.html
  src/main/resources/templates/fragments/head/view-post-head.html
  src/main/resources/templates/post/view-post.html
Labels: develop

#89 [Feature/Front/Error-Js] 게시판 조회시 토큰 만료 예외 메시지 출력
  src/main/resources/static/assets/js/main.js
  src/main/resources/static/js/member/ajax-error.js
  src/main/resources/static/js/member/login.js
  src/main/resources/static/js/member/member-edit.js
  src/main/resources/static/js/member/sign-up.js
  src/main/resources/static/js/post/update-post.js
  src/main/resources/static/js/post/view-post.js
  src/main/resources/templates/fragments/head/member-edit-head.html
Labels: develop
